In [1]:
%cd /home/parthgandhi/Projects/MLBot/mlbot

/home/parthgandhi/Projects/MLBot/mlbot

In [2]:
import polars as pl
import polars.selectors as cs
from src.swing_model.features import gen_features, gen_target
from src.swing_model.loader import gen_scanner_list, gen_stocks_list
from datetime import datetime
import glob

In [3]:
data = pl.scan_parquet("src/test_data.parquet")

In [4]:
START_TIME = datetime(2025, 1, 1)
END_TIME = datetime(2026, 4, 1)

In [5]:
stocks_list = gen_stocks_list(
    files_list=glob.glob("/home/parthgandhi/data/bhavcopy/NSE-Data-bank/data/*.csv"),
    start_date=START_TIME,
    end_date=END_TIME,
)

In [6]:
scanner_stocks = gen_scanner_list(data=data)

In [7]:
scanner_df = (
    scanner_stocks.join(stocks_list, on="timestamp", how="left")
    .filter(pl.col("symbol_count").is_not_null())
    .with_columns(pl.col("symbol").is_in(pl.col("symbol_right")).alias("eq_flag"))
    .filter(pl.col("eq_flag") == True)
    .select("timestamp", "symbol")
    .with_columns(pl.lit(True).alias("scan_flag"))
    .collect()
)

stocks = scanner_df.get_column("symbol").unique().to_list()

In [8]:
len(stocks)

813

In [9]:
ftr = gen_features(data=data).filter(pl.col("symbol").is_in(stocks))
target = gen_target(data=data).filter(pl.col("symbol").is_in(stocks))
res = ftr.join(target, on=["symbol", "timestamp"], how="left")

res = (
    res.with_columns(
        (pl.col("timestamp") - pl.duration(days=1)).alias("timestamp_prev_1")
    )
    .join(
        scanner_df.lazy(),
        left_on=["timestamp_prev_1", "symbol"],
        right_on=["timestamp", "symbol"],
        how="left",
    )
    .filter(pl.col("scan_flag"))
    .select(pl.exclude("scan_flag", "timestamp_prev_1"))
    .drop_nulls()
)

res = res.collect()

In [10]:
print(res.shape)
print(res.get_column("timestamp").min(), res.get_column("timestamp").max())
print(res.get_column("symbol").unique().shape)

(12507, 39)
2025-10-29 2026-04-02
(614,)

In [19]:
res.with_columns(
    pl.col("timestamp").dt.year().alias("year"),
    pl.col("timestamp").dt.month().alias("month"),
).group_by("year", "month", "target").len().sort("year", "month", "target").to_pandas()

    year  month  target   len
0   2025     10   False   590
1   2025     10    True   134
2   2025     11   False  2587
3   2025     11    True   530
4   2025     12   False  1812
5   2025     12    True   489
6   2026      1   False  1729
7   2026      1    True   342
8   2026      2   False  2310
9   2026      2    True   625
10  2026      3   False  1161
11  2026      3    True   104
12  2026      4   False    44
13  2026      4    True    50

In [30]:
res.group_by("target").agg(
    pl.col("std_9_21_dispersion_10").mean().alias("avg_dst_52W")
)

shape: (2, 2)
┌────────┬─────────────┐
│ target ┆ avg_dst_52W │
│ ---    ┆ ---         │
│ bool   ┆ f64         │
╞════════╪═════════════╡
│ false  ┆ 22.340324   │
│ true   ┆ 22.375927   │
└────────┴─────────────┘

In [22]:
res.filter(pl.col("target")).sample(10)

shape: (10, 39)
┌───────────┬────────────┬────────────┬───────────┬───┬───────────┬───────────┬───────────┬────────┐
│ symbol    ┆ timestamp  ┆ is_green_c ┆ close_pos ┆ … ┆ atr_ratio ┆ atr_pct_2 ┆ adr_pct_2 ┆ target │
│ ---       ┆ ---        ┆ andle      ┆ ition_in_ ┆   ┆ _14_50    ┆ 0         ┆ 0         ┆ ---    │
│ str       ┆ date       ┆ ---        ┆ range     ┆   ┆ ---       ┆ ---       ┆ ---       ┆ bool   │
│           ┆            ┆ bool       ┆ ---       ┆   ┆ f64       ┆ f64       ┆ f64       ┆        │
│           ┆            ┆            ┆ f64       ┆   ┆           ┆           ┆           ┆        │
╞═══════════╪════════════╪════════════╪═══════════╪═══╪═══════════╪═══════════╪═══════════╪════════╡
│ APEX      ┆ 2025-12-16 ┆ true       ┆ 0.7919    ┆ … ┆ 0.9555    ┆ 0.0519    ┆ 0.004     ┆ true   │
│ MMFL      ┆ 2026-02-18 ┆ true       ┆ 0.8353    ┆ … ┆ 1.154     ┆ 0.0517    ┆ 0.0022    ┆ true   │
│ CUPID     ┆ 2025-12-16 ┆ true       ┆ 0.8226    ┆ … ┆ 1.1153    ┆ 0.0368    ┆ 0.0124    ┆ true   │
│ PASHUPATI ┆ 2026-02-17 ┆ true       ┆ 0.8197    ┆ … ┆ 1.2973    ┆ 0.0471    ┆ 0.0116    ┆ true   │
│ SAKAR     ┆ 2025-11-26 ┆ false      ┆ 0.2967    ┆ … ┆ 1.0718    ┆ 0.0477    ┆ 0.0029    ┆ true   │
│ RAJRATAN  ┆ 2025-12-10 ┆ false      ┆ 0.0941    ┆ … ┆ 1.0408    ┆ 0.0514    ┆ 0.0024    ┆ true   │
│ KMEW      ┆ 2025-12-23 ┆ false      ┆ 0.5547    ┆ … ┆ 1.3642    ┆ 0.0745    ┆ 0.0006    ┆ true   │
│ PFOCUS    ┆ 2026-02-20 ┆ false      ┆ 0.0789    ┆ … ┆ 1.1575    ┆ 0.0669    ┆ 0.0041    ┆ true   │
│ PRECWIRE  ┆ 2026-02-13 ┆ false      ┆ 0.1704    ┆ … ┆ 1.1442    ┆ 0.0546    ┆ 0.004     ┆ true   │
│ JAMNAAUTO ┆ 2025-12-10 ┆ false      ┆ 0.5581    ┆ … ┆ 1.27      ┆ 0.0384    ┆ 0.0085    ┆ true   │
└───────────┴────────────┴────────────┴───────────┴───┴───────────┴───────────┴───────────┴────────┘